#!/bin/bash

# file SysInfoProject
# brief  The first script to gather system info with commenting for the file and functions 
# author brandon.boras
# date 10/20/2020

    #functions

# creates a title with a passed in string, uses default if nothing was passed in
GenerateTitle()
{
	printf "		 *** %s's stats report at " $(whoami)
	CURRENTDATE=`date +"%Y-%m-%d %T"`
	echo "${CURRENTDATE}" " ***"
}

# basic info including the distro,kernel version and CPU architecture
BasicInfo()
{
	printf "_____1. Basic Info_____\n"
	lsb_release -d
	printf "Kernel: "
    uname -r
	printf "CPU Architecture: "
	uname -m
}

# finds all the info related to memory
MemoryInfo()
{
	printf "\n\n_____2. Memory_____\n"
	free -ht
}

# displays disk information,lists disk devices,free space on partitions
DiskInfo()
{
	printf "\n\n_____3. Disks_____\n"
	lsblk
}

# checks if shell is interactive, then prompt to include groups
IncludeGroupsCheck()
{
	printf "\n\n_____4. User groups (prompted)_____\n"
	if [ -z "$PS1" ]; then
		read -p "Should I print your user groups too? (Y/N): "  userReply
		if [[  $userReply =~ ^[Yy]$ ]]; then
			groups
		else
			printf "Noted, will not print groups"
		fi
	else
		printf "This was not detected as an interactive shell, so I cannot print groups\n"
	fi
}

# prints the ip address of the hos
GetIP()
{
	printf "\n\n_____5. IP Address_____\n"
	hostname -I
}
		# main program begins here

if [ "$EUID" -ne 0 ]; then
	echo "Must Run as Root"
else
    # Here script
	cat <<- _EOF_

	$(GenerateTitle)
	$(BasicInfo)
	$(MemoryInfo)
	$(DiskInfo)
	$(IncludeGroupsCheck)
	$(GetIP)

	_EOF_
fi
exit 0
